import aboutItem1 from "../images/about/about-item1.png";
import aboutItem2 from "../images/about/about-item2.png";
import aboutItem3 from "../images/about/about-item3.png";
import aboutItem4 from "../images/about/about-item4.png";

import card1 from "../images/cards/card1.png";
import card2 from "../images/cards/card2.png";
import card3 from "../images/cards/card3.png";
import card4 from "../images/cards/card4.png";
import card5 from "../images/cards/card5.png";
import card6 from "../images/cards/card6.png";
import card7 from "../images/cards/card7.png";
import card8 from "../images/cards/card8.png";
import card9 from "../images/cards/card9.png";
import card10 from "../images/cards/card10.png";
import card11 from "../images/cards/card11.png";
import card12 from "../images/cards/card12.png";
import cardInfoMini1 from "../images/cards/cardInfoMini1.png";
import cardInfoMini2 from "../images/cards/cardInfoMini2.png";
import cardInfoMini3 from "../images/cards/cardInfoMini3.png";

export const tobBarFiltersObj = {
    all: false,
    sale: false,
    inStock: false,
    soldOut: false,
};

export const artistsSideBarObj = {
    all: false,
    machine56: false,
    sayaWorks: false,
    glitchNetwork: false,
    birdy: false,
    eez: false,
    kmr: false,
    konrtolaltdelt: false,
};

export const productsSideBarObj = {
    all: false,
    jackets: false,
    hoodies: false,
    sweatshirts: false,
    tees: false,
    pants: false,
    backpacks: false,
    hoodiesTshirt: false,
    vaultHunters: false,
    boneheadHelmets: false,
    demonPlateSeries: false,
    hfBat: false,
    masks: false,
    moleskineJackets: false,
    wallArts: false,
    figures: false,
    stickerPacksters: false,
    vectorPacksfBat: false,
    posters: false,
    fonts: false,
};

export const points = [
    {
        id: 1,
        text: "Follow us in different social networks to have information about our shop and our clothing",
        link1: "Instagram",
        link2: "Facebook",
    },
    {
        id: 2,
        text: "Machine 56 official web-shop present to you wear of future and give you perfect opportunity to get any cool clothing",
        link1: "Shop",
    },
    {
        id: 3,
        text: "If you want to find here some  small prices, you can chek out our sales page and choose  something",
        link1: "Sales",
    },
    {
        id: 4,
        text: "Have any questions? You can send us a letter using special page of our site and we will  answer you",
        link1: "Send message",
    },
    {
        id: 5,
        text: "If you are local customer of our shop (Indonesia), please, directly shop on our official Tokopedia page",
        link1: "Tokopedia",
    },
];

export const footerInfo = [
    {
        id: 1,
        title: "Networks",
        links: [
            {
                name: "Instagram",
                link: "/instagram",
            },
            {
                name: "Facebook",
                link: "/facebook",
            },
            {
                name: "Behance",
                link: "/behance",
            },
        ],
        href: true,
    },
    {
        id: 2,
        title: "Menu",
        links: [
            {
                name: "Home",
                link: "/",
            },
            {
                name: "Products",
                link: "/products",
            },
            {
                name: "Artists",
                link: "/artists",
            },
            {
                name: "Contact us",
                link: "/contacts",
            },
            {
                name: "About",
                link: "/about",
            },
        ],
    },
    {
        id: 3,
        title: "Products",
        links: [
            {
                name: "Jackets",
                link: "/products",
            },
            {
                name: "Sweatshirts",
                link: "/products",
            },
            {
                name: "Hoodies",
                link: "/products",
            },
            {
                name: "Tees",
                link: "/products",
            },
            {
                name: "Hoodies + T-shirt packs",
                link: "/products",
            },
            {
                name: "Pants",
                link: "/products",
            },
            {
                name: "Backpacks/carriers",
                link: "/products",
            },
            {
                name: "Vault hunters",
                link: "/products",
            },
        ],
    },
    {
        id: 4,
        title: "Accessoires",
        links: [
            {
                name: "Bonehead helmets",
                link: "/artists",
            },
            {
                name: "Demon plate series",
                link: "/artists",
            },
            {
                name: "Hf/bat",
                link: "/artists",
            },
            {
                name: "Masks",
                link: "/artists",
            },
            {
                name: "Moleskine jackets",
                link: "/artists",
            },
            {
                name: "Wall arts",
                link: "/artists",
            },
            {
                name: "1/6 figures",
                link: "/artists",
            },
            {
                name: "Sticker packs",
                link: "/artists",
            },
            {
                name: "Vector packs",
                link: "/artists",
            },
            {
                name: "Posters",
                link: "/artists",
            },
            {
                name: "Fonts",
                link: "/artists",
            },
        ],
    },
];

export const aboutItem = [
    {
        id: 1,
        types: [
            "BK100-MD",
            "GD205-MD",
            "SV405-MD",
            "SV255-MD",
            "CF-Series",
            "NX-Series",
        ],
        image: aboutItem1,
        size: [
            {
                name: "S",
                width: "53",
                height: "74",
            },
            {
                name: "M",
                width: "56",
                height: "76",
            },
            {
                name: "L",
                width: "59",
                height: "78",
            },
            {
                name: "XL",
                width: "62",
                height: "80",
            },
            {
                name: "2XL",
                width: "65",
                height: "82",
            },
        ],
    },
    {
        id: 2,
        types: ["MS-BOMDER D1", "MS-BOMBER D2", "PANZER VR-G1", "PANZER VR-G2"],
        image: aboutItem2,
        size: [
            {
                name: "S",
                width: "63",
                height: "69",
            },
            {
                name: "M",
                width: "66",
                height: "72",
            },
            {
                name: "L",
                width: "69",
                height: "74",
            },
            {
                name: "XL",
                width: "71",
                height: "76",
            },
            {
                name: "2XL",
                width: "74",
                height: "79",
            },
        ],
    },
    {
        id: 3,
        types: [
            "B/TYPE56 OG-01",
            "B/TYPE56 GL-02",
            "B/TYPE56 WT-03",
            "B/TYPE56 BK-04",
            "BLACK BOMBER",
            "WHITE BOMBER",
        ],
        image: aboutItem3,
        size: [
            {
                name: "S",
                width: "59",
                height: "66",
            },
            {
                name: "M",
                width: "62",
                height: "68",
            },
            {
                name: "L",
                width: "65",
                height: "70",
            },
            {
                name: "XL",
                width: "68",
                height: "72",
            },
            {
                name: "2XL",
                width: "71",
                height: "74",
            },
        ],
    },
    {
        id: 4,
        types: ["M56BD7-V2/BK", "M56BD7-V2RD"],
        image: aboutItem4,
        size: [
            {
                name: "S",
                width: "58",
                height: "80",
            },
            {
                name: "M",
                width: "59",
                height: "81",
            },
            {
                name: "L",
                width: "60",
                height: "82",
            },
            {
                name: "XL",
                width: "63",
                height: "81",
            },
            {
                name: "2XL",
                width: "62",
                height: "84",
            },
        ],
    },
];

export const items = [
    {
        id: 1,
        name: "MS-BOMBER D3",
        price: 135,
        image: card1,
        isSold: false,
        author: "machine56",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "jackets",
        accessories: "boneheadHelmets",
    },
    {
        id: 2,
        name: "HELMET",
        price: 100,
        image: card2,
        isSold: false,
        sale: true,
        author: "machine56",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "jackets",
        accessories: "boneheadHelmets",
    },
    {
        id: 3,
        name: "HELMET",
        price: 130,
        image: card3,
        isSold: true,
        author: "machine56",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "jackets",
        accessories: "boneheadHelmets",
    },
    {
        id: 4,
        name: "MS-BOMBER D3",
        price: 175,
        image: card4,
        isSold: false,
        sale: true,
        author: "machine56",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "jackets",
        accessories: "boneheadHelmets",
    },
    {
        id: 5,
        name: "MS-BOMBER D3",
        price: 140,
        image: card5,
        isSold: false,
        sale: true,
        author: "machine56",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "jackets",
        accessories: "demonPlateSeries",
    },
    {
        id: 6,
        name: "MS-BOMBER D3",
        price: 200,
        image: card6,
        isSold: false,
        author: "machine56",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "hoodies",
        accessories: "demonPlateSeries",
    },
    {
        id: 7,
        name: "MS-BOMBER D3",
        price: 235,
        image: card7,
        isSold: true,
        author: "sayaWorks",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "hoodies",
        accessories: "demonPlateSeries",
    },
    {
        id: 8,
        name: "MS-BOMBER D3",
        price: 130,
        image: card8,
        isSold: false,
        sale: true,
        author: "sayaWorks",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "hoodies",
        accessories: "hfBat",
    },
    {
        id: 9,
        name: "MS-BOMBER D3",
        price: 200,
        image: card9,
        isSold: true,
        author: "sayaWorks",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "hoodies",
        accessories: "hfBat",
    },
    {
        id: 10,
        name: "MS-BOMBER D3",
        price: 340,
        image: card10,
        isSold: false,
        sale: true,
        author: "sayaWorks",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "hoodies",
        accessories: "hfBat",
    },
    {
        id: 11,
        name: "MS-BOMBER D3",
        price: 140,
        image: card11,
        isSold: false,
        sale: true,
        author: "glitchNetwork",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "hoodies",
        accessories: "hfBat",
    },
    {
        id: 12,
        name: "MS-BOMBER D3",
        price: 150,
        image: card12,
        isSold: false,
        sale: true,
        author: "glitchNetwork",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "sweatshirts",
        accessories: "hfBat",
    },
    {
        id: 13,
        name: "MS-BOMBER D3",
        price: 135,
        image: card1,
        isSold: false,
        sale: true,
        author: "glitchNetwork",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "sweatshirts",
        accessories: "masks",
    },
    {
        id: 14,
        name: "MS-BOMBER D3",
        price: 100,
        image: card2,
        isSold: false,
        author: "glitchNetwork",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "sweatshirts",
        accessories: "masks",
    },
    {
        id: 15,
        name: "MS-BOMBER D3",
        price: 130,
        image: card3,
        isSold: true,
        author: "glitchNetwork",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "sweatshirts",
        accessories: "masks",
    },
    {
        id: 16,
        name: "MS-BOMBER D3",
        price: 175,
        image: card5,
        isSold: false,
        author: "glitchNetwork",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "sweatshirts",
        accessories: "masks",
    },
    {
        id: 17,
        name: "MS-BOMBER D3",
        price: 140,
        image: card12,
        isSold: false,
        author: "birdy",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "sweatshirts",
        accessories: "moleskineJackets",
    },
    {
        id: 18,
        name: "MS-BOMBER D3",
        price: 200,
        image: card6,
        isSold: false,
        author: "birdy",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "tees",
        accessories: "moleskineJackets",
    },
    {
        id: 19,
        name: "MS-BOMBER D3",
        price: 235,
        image: card7,
        isSold: true,
        author: "birdy",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "tees",
        accessories: "moleskineJackets",
    },
    {
        id: 20,
        name: "MS-BOMBER D3",
        price: 130,
        image: card1,
        isSold: true,
        author: "birdy",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "tees",
        accessories: "moleskineJackets",
    },
    {
        id: 21,
        name: "MS-BOMBER D3",
        price: 200,
        image: card9,
        isSold: false,
        author: "birdy",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "tees",
        accessories: "wallArts",
    },
    {
        id: 22,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        name: "MS-BOMBER D3",
        price: 340,
        image: card10,
        isSold: false,
        sale: true,
        author: "eez",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        clothing: "pants",
        accessories: "wallArts",
    },
    {
        id: 23,
        name: "MS-BOMBER D3",
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        price: 140,
        image: card11,
        isSold: false,
        author: "eez",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        clothing: "pants",
        accessories: "wallArts",
    },
    {
        id: 24,
        name: "MS-BOMBER D3",
        price: 150,
        image: card12,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        isSold: false,
        sale: true,
        author: "eez",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        clothing: "pants",
        accessories: "figures",
    },
    {
        id: 25,
        name: "MS-BOMBER D3",
        price: 135,
        image: card1,
        isSold: false,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        sale: true,
        author: "glitchNetwork",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        clothing: "backpacks",
        accessories: "figures",
    },
    {
        id: 26,
        name: "MS-BOMBER D3",
        price: 100,
        image: card2,
        isSold: false,
        author: "glitchNetwork",
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        clothing: "backpacks",
        accessories: "figures",
    },
    {
        id: 27,
        name: "MS-BOMBER D3",
        price: 130,
        image: card3,
        isSold: true,
        sale: true,
        author: "kmr",
        cardInfoMini1: cardInfoMini1,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        clothing: "backpacks",
        accessories: "stickerPacksters",
    },
    {
        id: 28,
        name: "MS-BOMBER D3",
        price: 175,
        image: card4,
        isSold: false,
        author: "kmr",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "backpacks",
        accessories: "stickerPacksters",
    },
    {
        id: 29,
        name: "MS-BOMBER D3",
        price: 140,
        image: card5,
        isSold: false,
        author: "kmr",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "hoodiesTshirt",
        accessories: "vectorPacksfBat",
    },
    {
        id: 30,
        name: "MS-BOMBER D3",
        price: 130,
        image: card6,
        isSold: false,
        author: "konrtolaltdelt",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "hoodiesTshirt",
        accessories: "vectorPacksfBat",
    },
    {
        id: 31,
        name: "MS-BOMBER D3",
        price: 235,
        image: card7,
        isSold: true,
        author: "konrtolaltdelt",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "hoodiesTshirt",
        accessories: "vectorPacksfBat",
    },
    {
        id: 32,
        name: "MS-BOMBER D3",
        price: 130,
        image: card8,
        isSold: false,
        author: "konrtolaltdelt",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "hoodiesTshirt",
        accessories: "posters",
    },
    {
        id: 33,
        name: "MS-BOMBER D3",
        price: 200,
        image: card9,
        isSold: true,
        author: "konrtolaltdelt",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "vaultHunters",
        accessories: "posters",
    },
    {
        id: 34,
        name: "MS-BOMBER D3",
        price: 340,
        image: card10,
        isSold: false,
        author: "konrtolaltdelt",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "vaultHunters",
        accessories: "posters",
    },
    {
        id: 35,
        name: "MS-BOMBER D3",
        price: 140,
        image: card11,
        isSold: false,
        author: "birdy",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "vaultHunters",
        accessories: "fonts",
    },
    {
        id: 36,
        name: "MS-BOMBER D3",
        price: 150,
        image: card12,
        isSold: true,
        author: "glitchNetwork",
        cardInfoMini1: cardInfoMini1,
        cardInfoMini2: cardInfoMini2,
        cardInfoMini3: cardInfoMini3,
        text1: "Upgraded Mauser School Bomber jacket. Armored Art, zero gravity combat specialist. D3 Version comes with detachable webbing on the back. Heavy duty and rugged material. packed with back pocket.",
        text2: "Model are 165cm height, wearing Medium size.",
        clothing: "vaultHunters",
        accessories: "fonts",
    },
];
